[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = '''
(
  /\.git
  | /\.oscanner
  | /\.pre-commit-cache
  | /\.pytest_cache
  | /__pycache__
  | /\.venv
  | /venv
  | /frontend
  | /logs
)
'''
